Fix UTF8 handling
miqwit/dedex pull request #31
Opened 2024-05-15 15:19 UTC by ignacioalles

Fix issue #30 by storing un-trimmed value in last element reference.

2024-06-02 19:15 UTC, miqwit commented
hello @ignacioalles. Any update on this?

2024-06-03 12:31 UTC, miqwit commented
Ha ok. Now it's clear, thanks. I've made a code review above, mentioning some improvement if you don't mind to update your PR. I can do it myself too, if you're fine with that.

2024-06-03 13:31 UTC, ignacioalles commented
I can't see your code review. Am I missing something? Also feel free to make any change you consider in my PR.

2024-06-03 13:55 UTC, miqwit requested changes

2024-06-03 15:12 UTC, ignacioalles commented on src/Controller/ErnParserController.php
> +      $value_clean = trim($value);
Sure!

2024-06-04 07:50 UTC, merged

2024-06-04 07:56 UTC, miqwit commented
It's merged and released in 2.0.7 @ignacioalles. Thank you for your contribution.
I'd like to make progress on [another PR](https://github.com/miqwit/dedex/pull/29) but I'd need former version of DDEX ERN messages. If you happen to be able to provide some (anonymised, removing Party IDs and renaming artists and track names), let me know, it would be greatly appreciated.

2024-06-04 14:46 UTC, ignacioalles commented
I don't have much information on samples of other ddex versions. I mainly use 3.8.2 but I think it is useful to have a way to support other versions without forking the entire project.